# Configurações da Aplicação PDF Converter
# ==========================================

# Configurações do Servidor
server:
  port: 8080
  servlet:
    context-path: /
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024

# Configurações Spring Boot
spring:
  application:
    name: PDF-Converter-App

  # Configurações de Upload de Arquivos
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 100MB
      file-size-threshold: 2KB
      location: ${java.io.tmpdir}

  # Configurações de Cache
  cache:
    type: simple
    cache-names: conversions, files

  # Configurações de Thread Pool
  task:
    execution:
      pool:
        core-size: 4
        max-size: 8
        queue-capacity: 500
        keep-alive: 60s
        thread-name-prefix: pdf-converter-
    scheduling:
      pool:
        size: 2
        thread-name-prefix: pdf-scheduler-

# Configurações de Storage
storage:
  location: upload-dir
  processed-location: processed-dir
  max-file-size: 52428800  # 50MB em bytes
  file-retention-minutes: 60
  allowed-file-types:
    - application/pdf
    - image/jpeg
    - image/png
    - image/gif
    - application/msword
    - application/vnd.openxmlformats-officedocument.wordprocessingml.document
    - application/vnd.ms-excel
    - application/vnd.openxmlformats-officedocument.spreadsheetml.sheet

# Configurações de Logging
logging:
  level:
    root: INFO
    com.pdfmanager: DEBUG
    org.springframework.web: INFO
    org.apache.pdfbox: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/pdf-converter.log
    max-size: 10MB
    max-history: 30

# Configurações de Segurança
security:
  cors:
    allowed-origins: "*"
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: "*"
    max-age: 3600

# Configurações de Performance
performance:
  pdf:
    compression-level: MEDIUM
    image-dpi: 300
    text-extraction-sorting: true
    optimize-resources: true

# Configurações de Monitoramento
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      simple:
        enabled: true

# Informações da Aplicação
info:
  app:
    name: PDF Converter Application
    description: Aplicação web para conversão e manipulação de PDFs
    version: 1.0.0
    contact:
      name: PDF Manager Team
      email: support@pdfconverter.com